Use Tracy

--Select * from [Online Retail]

--What are the top-selling products by quantity?
--Select Top 10 Description, Quantity, UnitPrice, Total from [Online Retail]
--Order by Quantity Desc

--What are the top-selling products by Revenue
--Select Top 10 Description, Quantity, UnitPrice, Total from [Online Retail]
--Order by Total Desc

--How often do customers repeat purchases?
--Select CustomerID, Count(*) AS Total_Orders, MIN(Invoice_Date) AS First_Invoice_Date, MAX(Invoice_Date) AS Last_Invoice_Date
--from [Online Retail]
--Group by CustomerID
--Having Count(*) > 1
--Order by Total_Orders DESC

 --Which countries have the highest sales volumes?
 --Select top 10 Country, SUM(Total) AS OverallTotal From [Online Retail]
 --Group by Country
 --Order by OverallTotal Desc

 --Which country has the least sales volumes?
 --Select top 1 Country, SUM(Total) AS OverallTotal From [Online Retail]
 --Group by Country
 --Order by OverallTotal Asc

 --Calculate the total revenue generated per invoice.
 --Select InvoiceNo, Sum(Quantity) AS Quantities, Sum(Total) As OverallTotal 
 --From [Online Retail]
 --Group by InvoiceNo

 --Find the total quantity of each product sold?
 --Select StockCode, Sum(Quantity) As Quantities From [Online Retail]
 --Group by StockCode

 --Get the total revenue generated by each customer.
 --Select CustomerID, Sum(Total) As OverallTotal From [Online Retail]
 --Group by CustomerID

 --Find the most purchased product in the dataset 
 --Select StockCode, Sum(Quantity) As Quantities From [Online Retail]
 --Group by StockCode
 --Order by Quantities Desc

 --List the top 5 customers by total spending
 --Select top 5 CustomerID, Sum(Total) As OverallTotal from [Online Retail]
 --Group by CustomerID
 --Order by OverallTotal Desc
 
 --Which year generated the most revenue?
 --Select Year(Invoice_Date), Sum(Total) As OverallTotal from [Online Retail]
 --Group by Year(Invoice_Date)
 --Order by OverallTotal Desc

 --Which Months recorded more salesand which month recorded the least sales?
 --Select Month(Invoice_Date), Sum(Total) As OverallTotal from [Online Retail]
 --Group by Month(Invoice_Date)
 --Order by OverallTotal Desc

 --Which country has the highest number of quantity purchased and which country has the least number of quantity purchased?
 --Select top 1 Country, SUM(Quantity) AS TotalQuantity From [Online Retail]
 --Group by Country
 --Order by TotalQuantity Desc

 --Select top 1 Country, SUM(Quantity) AS TotalQuantity From [Online Retail]
 --Group by Country
 --Order by TotalQuantity Asc
